# Loss or Cost Function

In [1]:
import numpy as np

y_true = np.array([0.30,0.7,1,0,0.5])
y_pred = np.array([1,1,0,0,1])

### Mean Absolute Error (MAE)

Implementing using normal Python function method

In [26]:
def mae(y_true, y_pred):
    total_error = 0
    for yt, yp in zip(y_true, y_pred):
        total_error += abs(yp - yt)
    print(f"Total Error:", total_error)
    mae = total_error / len(y_true)
    print(f"MAE: ", mae)

In [27]:
mae(y_true, y_pred)

Total Error: 2.5
MAE:  0.5


Implement using numpy framework which is more efficient and easier

In [39]:
np.abs(y_true - y_pred)

array([0.7, 0.3, 1. , 0. , 0.5])

In [31]:
print(np.sum(np.abs(y_true - y_pred)))
print(np.mean(np.abs(y_true - y_pred)))

2.5
0.5


In [37]:
def mae_np(y_pred, y_true):
    return np.mean(np.abs(y_pred - y_true))

In [38]:
mae_np(y_pred, y_true)

0.5

### Log Loss or Binary Cross Entropy

In [41]:
np.log([0])

/var/folders/6g/zbv6zp2s0yjfhrt83s_n6gj40000gn/T/ipykernel_92690/262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

Since we are getting undefined for log of 0 so we are using epsilon as the nearest number to 0 to avoid this error.

In [43]:
epsilon = 1e-10
np.log([1e-10])

array([-23.02585093])

In [44]:
y_pred

array([1, 1, 0, 0, 1])

In [46]:
y_pred_new = [max(i, epsilon) for i in y_pred]
y_pred_new

[1, 1, 1e-10, 1e-10, 1]

In [47]:
y_pred_new = [min(i, 1-epsilon) for i in y_pred_new]
y_pred_new

[0.9999999999, 0.9999999999, 1e-10, 1e-10, 0.9999999999]

In [48]:
y_pred_new = np.array(y_pred_new)

In [49]:
np.log(y_pred_new)

array([-1.00000008e-10, -1.00000008e-10, -2.30258509e+01, -2.30258509e+01,
       -1.00000008e-10])

In [51]:
-np.mean(y_true * np.log(y_pred_new) + (1 - y_true) * np.log(1 - y_pred_new))

11.51292544019812

In [59]:
def binary_crossentropy(y_pred, y_true):
    y_pred_new = [max(i, epsilon) for i in y_pred]
    y_pred_new = [min(i, 1-epsilon) for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    return -np.mean(y_true * np.log(y_pred_new) + (1 - y_true) * np.log(1 - y_pred_new))

In [60]:
binary_crossentropy(y_pred, y_true)

11.51292544019812