# Matrices in Deep Learning

Matrices are used to represent the weights and biases of the connections between the neurons in different layers of a neural network. When it comes to derivatives and partial derivatives, matrices are used to organize and compute the derivatives of functions with multiple inputs or multiple outputs.

For example, the gradient of a function with multiple inputs is a vector of partial derivatives, which can be organized into a matrix called the Jacobian matrix. The Jacobian matrix contains all first-order partial derivatives of a vector-valued function with respect to a vector of inputs.

Matrices are also used in the computation of the backpropagation algorithm, which is used to train neural networks by computing the gradient of the loss function with respect to the weights and biases of the network. The gradients are then used to update the weights and biases in the direction that minimally reduces the loss.

In [1]:
import numpy as np

- Calculate Profit/Loss from revenue and expenses

In [2]:
revenue = np.array([[180, 200, 220], [24, 36, 40], [12, 18, 20]])
expense = np.array([[80, 90, 100], [10, 16, 20], [8, 10, 10]])

In [6]:
profit_loss = revenue - expense
profit_loss

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

- Calculate total sales from units and price per unit using matrix multiplication


In [10]:
price_per_unit = np.array([1000, 400, 1200])
units = np.array([[30, 40, 50], [5, 10, 15], [2, 5, 7]])
price_per_unit * units # numpy broadcasting

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In above case numpy is using broadcasting so it expands price_per_unit array from 1 row, 3 columns to 3 row and 3 columns. Correct way to do matrix multiplication is to use dot product as shown below

In [12]:
total_sales = np.dot(price_per_unit, units) # numpy dot product
total_sales

array([34400, 50000, 64400])